### ISSUE TITLE
build error with not found Classes/Classes.h and IHttpRequest.h

### ISSUE THREAD

**Issue by dotcom** [netspeakgames/UnrealAgonesSDK#1]
I faced a build error and I share it

```
'Classes/Classes.h': No such file or directory
'IHttpRequest.h': No such file or directory
'IHttpResponse.h': No such file or directory
```

And, I modified the code as follows to avoid this error, is it correct?

AgonesComponent.cpp
```diff
- #include "Classes/Classes.h"
- #include "IHttpRequest.h"
- #include "IHttpResponse.h"
+ #include "Classes.h"
+ #include "Interfaces/IHttpRequest.h"
+ #include "Interfaces/IHttpResponse.h"
```

AgonesComponent.h
```diff
- #include "Classes/Classes.h"
- #include "IHttpRequest.h"
+ #include "Classes.h"
+ #include "Interfaces/IHttpRequest.h"
```

UE version=4.24.3-0+++Release-4.24 source build

**Comment by domgreen** [comment]
Thanks for reporting just been having a play with this.

Did you just compile this via the Visual Studio and which version of VS we are on 2019? Could be that how MSBuild works changes between the two.

```
0>Using Visual Studio 2019 14.26.28805 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801) and Windows 10.0.18362.0 SDK (C:\Program Files (x86)\Windows Kits\10).
```

Is compiling (ReBuild Solution) fine in UE-Rider and against our 4.25 on 2019 fork of the engine on Linux and Mac, with your suggested changes it also works fine so will commit them.

Also; your change is actually more technically correct 👍 

Gonna also remove the includes from the cpp file that are in the header file as they are not needed in both if they are in the header.

I will add this change locally and include it as I push this version of the SDK to Agones main.

**Comment by domgreen** [comment]
Thanks @dotcom issue has been addressed and merged in #googleforgames/agones/1739
